meta:
  run-mode: debug
  port: 10001
  log-path: log/console.log

jwt:
  secret: 9C27D0C7C04BDA8A1F1B099CF4F9B1956AF5164F
  issuer: rbac.learn.auth
  expire: 3600 # second
  refresh-expire: 7200 # second

casbin:
  config-path: src/config/rbac-model.conf
