meta:
  run-mode: debug
  port: 10001
  log-path: ./log/console.log
  def-page-size: 10
  max-page-size: 30

mysql:
  host: 127.0.0.1
  port: 3306
  name: db_rbac
  charset: utf8
  user: root
  password: 123
  log: true

redis:
  conn-type: tcp
  host: 127.0.0.1
  port: 6379
  db: 1
  password: 123
  connect-timeout: 1000 # microsecond
  read-timeout: 1000
  write-timeout: 1000

jwt:
  secret: xxx
  issuer: rbac.learn.auth
  expire: 3600 # second
  refresh-expire: 7200 # second
  redis-fmt: rbac-learn-token-%s-%s # uid-token
  fake: # only used when debug mode
    xxx_root: 1
    xxx_admin: 3
    xxx_normal: 4

casbin:
  config-path: ./config/rbac-model.conf
